# Generated by Django 4.0.1 on 2022-03-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='customer',
        ),
    ]
