# Generated by Django 4.0.1 on 2022-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_users_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='password3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
