# Generated by Django 4.0.1 on 2022-03-23 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwd1', to='home.image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwd2', to='home.image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwd3', to='home.image'),
        ),
    ]
